#!/bin/bash
# @script   : pre-commit
# @created  : 2013-05-24 23:56
# @changed  : 2013-05-26 03:04
# @revision : 6
# @about    : git pre-commit hook

# file names in the current commit (except removed)
for name in `git diff --cached --name-only --diff-filter=ACM`; do
    # check extension
    ext=$(echo $name | grep -Po "\.(py|rb|lua)$")
    # watching python | ruby | lua scripts
    if [ ! -z $ext ]; then
        script=$name
        # modify changed time
        dt=$(date "+%Y-%m-%d %H:%M")
        sed -i -r "s/(@changed.*)[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}/\1$dt/g" $script
        # increment revision number
        revision=`grep -E ^.*@revision.*[0-9]+$ $script | awk '{n=$NF+1; sub(/[0-9]+$/,n) }1'`
        sed -i -r "s/^.*@revision.*[0-9]+$/$revision/" $script
        # add changes to commit
        `git add $script`
    fi
done

# if exit status other then 0 commit will fail
# in an emergency the hook can be bypassed by passing –no-verify:
# $ git commit --no-verify ...
exit 0
